# Site Settings
title: Resume - Jesse Stippel
url: 'https://netroxen.github.io'
baseurl: '/'
description: The Resume of Jesse Ian Stippel
theme_skin: ceramic
chrome_mobile_color:

# Tracker
analytics:

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  
# Build Settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
